Stop users from entering path-segments in file matchers
The BFG uses the fact that it doesn't support path-matching (only
file-matching) to perform tree-by-tree instead of
commit-tree-by-commit-tree cleaning. This yields a big performance
increase, but users need to be aware that they can not search by
path-matchers.

The CLI parser now gives an error message like this:

$ bfg -D src/Class.java
Error: option delete-files failed when given 'src/Class.java'. *** Can only match on filename, NOT path *** - remove '/' path segments


Many thanks to Bill Hunt for pointing out this usability issue!